
// COMPILER OPTIMISATIONS -- You can set this to [1] if using many null properties, otherwise leave it as [0]
#macro TGMS_OPTIMISE_NULL_PROPERTY 0

// TWEEN PLAY MODES
#macro TWEEN_MODE_ONCE 0
#macro TWEEN_MODE_BOUNCE 1
#macro TWEEN_MODE_PATROL 2
#macro TWEEN_MODE_LOOP 3
#macro TWEEN_MODE_REPEAT 4

// TWEEN EVENT TYPES
#macro TWEEN_EV_PLAY 0
#macro TWEEN_EV_FINISH 1
#macro TWEEN_EV_STOP 2
#macro TWEEN_EV_PAUSE 3
#macro TWEEN_EV_RESUME 4
#macro TWEEN_EV_CONTINUE 5
#macro TWEEN_EV_REVERSE 6
#macro TWEEN_EV_STOP_DELAY 7
#macro TWEEN_EV_PAUSE_DELAY 8
#macro TWEEN_EV_RESUME_DELAY 9
#macro TWEEN_EV_FINISH_DELAY 10

// TWEEN USER PROPERTIES
#macro TWEEN_USER_VALUE global.TGMS_USER_VALUE
#macro TWEEN_USER_TARGET global.TGMS_USER_TARGET
#macro TWEEN_USER_GET global.TGMS_TWEEN_USER_GET
#macro TWEEN_USER_DATA global.TGMS_USER_DATA
